version: "3.0"
services:
    app:
        build: ./Rails
        ports:
            - 80:3000
        volumes:
            - ./Rails/src:/app
        depends_on:
            - db
        tty: true
        restart: always

    db:
        image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: todo_app
        ports:
          - "3306:3306"
