name: Test

on:
  pull_request:
    branches:
      - develop
    paths:
      - "Rails/src"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up -d db
      - run: docker-compose build
      - run: docker-compose run app rails db:create
      - run: docker-compose run app rails db:migrate
      - run: docker-compose run app bundle exec rspec spec
