name: Test

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Hello World
        run: echo "Hello, World"
